import { DotRing } from './TelemetryVisuals';
import React, { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { AlertLevel, Health } from '../models';
import { colors, radius, spacing } from '../theme';

export function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <View style={styles.sectionRow}><Text style={styles.section}>{title}</Text>{action}</View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: object }) { return <View testID="surface-card" style={[styles.card, style]}>{children}</View>; }
export function StatusBadge({ status, label }: { status: Health | AlertLevel | 'running' | 'stopped'; label?: string }) { const color = status === 'online' || status === 'running' || status === 'info' ? colors.green : status === 'warning' ? colors.yellow : status === 'error' ? colors.orange : colors.red; return <View style={[styles.badge, { borderColor: `${color}55`, backgroundColor: `${color}15` }]}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={[styles.badgeText, { color }]}>{label ?? status.toUpperCase()}</Text></View>; }
export function MetricCard({ icon, label, value, detail, color = colors.blue, percent, luminous = false }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; detail?: string; color?: string; percent?: number | null; luminous?: boolean }) { return <Card style={styles.metric}><div className={`metric-atmosphere ${luminous ? 'luminous' : ''}`} style={{ background: `radial-gradient(ellipse at 100% 100%, ${color}35, transparent 70%)` }} />{percent !== undefined && <DotRing value={percent} color={color} />}<View style={[styles.icon, { backgroundColor: `${color}18` }]}><Ionicons name={icon} size={16} color={color} /></View><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, luminous && { color }]}>{value}</Text>{detail ? <Text style={styles.detail}>{detail}</Text> : null}</Card>; }
export function PageHeader({ eyebrow, title, right }: { eyebrow?: string; title: string; right?: React.ReactNode }) { return <View style={styles.header}><View>{eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}<Text style={styles.title}>{title}</Text></View>{right}</View>; }
export function StateView({ kind = 'error', message, onRetry }: { kind?: 'loading' | 'error' | 'offline' | 'unauthorized' | 'empty'; message?: string; onRetry?: () => void }) { if (kind === 'loading') return <View style={styles.state}><ActivityIndicator color={colors.blue} /><Text style={styles.muted}>Loading monitoring data…</Text></View>; const icon = kind === 'offline' ? 'cloud-offline-outline' : kind === 'unauthorized' ? 'lock-closed-outline' : kind === 'empty' ? 'file-tray-outline' : 'warning-outline'; return <View style={styles.state}><Ionicons name={icon} size={30} color={colors.muted} /><Text style={styles.stateTitle}>{kind === 'empty' ? 'Nothing here yet' : kind === 'unauthorized' ? 'Session expired' : 'Unable to load data'}</Text><Text style={styles.muted}>{message ?? 'Unable to connect to monitoring API.'}</Text>{onRetry ? <Pressable onPress={onRetry} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable> : null}</View>; }
export function ActionButton({ title, icon, onPress, danger = false, disabled = false }: { title: string; icon: keyof typeof Ionicons.glyphMap; onPress: () => void; danger?: boolean; disabled?: boolean }) { const [hovered, setHovered] = useState(false); return <Pressable accessibilityRole="button" onHoverIn={() => setHovered(true)} onHoverOut={() => setHovered(false)} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.action, hovered && { backgroundColor: '#303841', borderColor: '#53616c' }, danger && styles.actionDanger, (pressed || disabled) && { opacity: 0.65 }]}><Ionicons name={icon} size={18} color={danger ? colors.red : colors.blue} /><Text style={[styles.actionText, danger && { color: colors.red }]}>{title}</Text></Pressable>; }
const styles = StyleSheet.create({ sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, section: { fontSize: 14, fontWeight: '600', color: colors.text, letterSpacing: -0.2 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.lg }, badge: { alignSelf: 'flex-start', borderWidth: 1, borderRadius: radius.pill, paddingVertical: 4, paddingHorizontal: 8, flexDirection: 'row', gap: 6, alignItems: 'center' }, dot: { width: 6, height: 6, borderRadius: 6 }, badgeText: { fontSize: 10, lineHeight: 14, fontWeight: '600', letterSpacing: 0.5 }, metric: { position: 'relative', overflow: 'hidden', flex: 1, minWidth: 180, flexBasis: 180, gap: 8 }, icon: { width: 28, height: 28, borderRadius: 7, alignItems: 'center', justifyContent: 'center', marginBottom: 4 }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', letterSpacing: 0.5 }, metricValue: { color: colors.text, fontSize: 29, fontWeight: '500', letterSpacing: -1.1 }, detail: { color: colors.muted, fontSize: 11 }, header: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between', alignItems: 'flex-end' }, eyebrow: { color: colors.subtle, fontSize: 10, letterSpacing: 1.7, fontWeight: '600', marginBottom: 8 }, title: { color: colors.text, fontSize: 30, fontWeight: '600', letterSpacing: -1 }, state: { alignItems: 'center', justifyContent: 'center', gap: 10, paddingTop: 100, paddingHorizontal: 30 }, stateTitle: { color: colors.text, fontSize: 17, fontWeight: '700' }, muted: { color: colors.muted, fontSize: 13, textAlign: 'center' }, retry: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, paddingVertical: 8, paddingHorizontal: 16, marginTop: 4 }, retryText: { color: colors.blue, fontWeight: '700' }, action: { minHeight: 44, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingHorizontal: 12 }, actionDanger: { borderColor: '#f851494d' }, actionText: { color: colors.blue, fontSize: 13, fontWeight: '700' } });
